spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        security: debug
auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168

