spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: FrBrUkwv2ek0nx10
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
auth:
  jwt:
    issuer: team.sparta.localconcert.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 1
    refreshTokenExpirationHour: 24

